/**
 * Build-time script: Reads image assets from public/ and generates
 * a TypeScript file with base64-encoded constants.
 * This avoids readFileSync at runtime (which won't work on Vercel serverless).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'

const ROOT = process.cwd()
const PUBLIC = join(ROOT, 'public')
const OUT_DIR = join(ROOT, 'src', 'lib', 'generated')
const OUT_FILE = join(OUT_DIR, 'assets.ts')

function toBase64(filename: string): string {
  const filePath = join(PUBLIC, filename)
  try {
    const buf = readFileSync(filePath)
    const ext = filename.split('.').pop()?.toLowerCase()
    const mime = ext === 'svg' ? 'image/svg+xml' : ext === 'jpg' ? 'image/jpeg' : 'image/png'
    return `data:${mime};base64,${buf.toString('base64')}`
  } catch (e) {
    console.warn(`⚠️  Could not read ${filename}:`, e)
    return ''
  }
}

// Assets to embed
const assets = {
  logoMain: toBase64('Logo-main.png'),
  footerPin: toBase64('footer-pin.png'),
}

// Generate TypeScript file
const content = `// ⚠️ AUTO-GENERATED FILE — do not edit manually
// Generated by scripts/generate-assets.ts at build time

export const LOGO_BASE64 = ${JSON.stringify(assets.logoMain)}
export const FOOTER_PIN_BASE64 = ${JSON.stringify(assets.footerPin)}
`

mkdirSync(OUT_DIR, { recursive: true })
writeFileSync(OUT_FILE, content, 'utf-8')
console.log('✅ Generated src/lib/generated/assets.ts')
console.log(`   Logo: ${assets.logoMain ? assets.logoMain.length + ' chars' : 'MISSING'}`)
console.log(`   Footer Pin: ${assets.footerPin ? assets.footerPin.length + ' chars' : 'MISSING'}`)
