'use client'
import { useDocumentForm } from '@/hooks/useDocumentForm'
import { EmployeeSelect } from './EmployeeSelect'
import { FormField } from './FormField'
import { MismatchModal } from './MismatchModal'
import { Separator } from '@/components/ui/separator'
import { Button } from '@/components/ui/button'
import type { Employee } from '@/lib/storage'
import { validateRequiredFields } from '@/lib/validate'
interface BankIntroLetterFormData { name: string; designation: string; department: string; ref_code: string; date: string; employee_id: string; bank_name: string; bank_branch: string; joining_date: string }
const initialData: BankIntroLetterFormData = { name: '', designation: '', department: '', ref_code: '', date: new Date().toISOString().slice(0, 10), employee_id: '', bank_name: '', bank_branch: '', joining_date: '' }
function mapEmployeeToForm(emp: Employee): Partial<BankIntroLetterFormData> { return { name: emp.name, designation: emp.designation, department: emp.department, ref_code: emp.ref_code, employee_id: emp.id, joining_date: emp.joining_date } }
function onCalculate(_d: BankIntroLetterFormData): Partial<BankIntroLetterFormData> { return {} }
export function BankIntroLetterForm() {
  const h = useDocumentForm({ docType: 'bank_intro_letter', initialData, mapEmployeeToForm, onCalculate, validate: (d) => validateRequiredFields(d, { name: { required: true, label: 'Name' }, designation: { required: true, label: 'Designation' }, bank_name: { required: true, label: 'Bank name' } }) })
  const { formData, setField, selectedEmployeeId, handleEmployeeChange, employees, mismatches, showMismatchModal, setShowMismatchModal, handleGenerate, handleMismatchAction, generated, errors } = h
  const show = selectedEmployeeId && selectedEmployeeId !== '__new__'
  return <div className="flex flex-col h-full"><div className="flex-1 overflow-y-auto"><div className="p-4 space-y-4"><EmployeeSelect employees={employees} value={selectedEmployeeId} onChange={handleEmployeeChange} />{selectedEmployeeId === '__new__' && <div className="text-center text-xs text-gray-500 p-3 bg-gray-50 rounded-lg border border-gray-200">Please add employee first</div>}{show && <><Separator /><div className="space-y-3"><h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Employee Info</h4><div className="grid grid-cols-2 gap-x-3 gap-y-1"><FormField label="Name" value={formData.name} onChange={v => setField('name', v)} error={errors.name} /><FormField label="Designation" value={formData.designation} onChange={v => setField('designation', v)} error={errors.designation} /><FormField label="Department" value={formData.department} onChange={v => setField('department', v)} /><FormField label="Employee ID" value={formData.employee_id} onChange={v => setField('employee_id', v)} /><FormField label="Ref Code" value={formData.ref_code} onChange={v => setField('ref_code', v)} /><FormField label="Joining Date" type="date" value={formData.joining_date} onChange={v => setField('joining_date', v)} /></div></div><Separator /><div className="space-y-3"><h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Bank Details</h4><div className="grid grid-cols-2 gap-x-3 gap-y-1"><FormField label="Bank Name" value={formData.bank_name} onChange={v => setField('bank_name', v)} error={errors.bank_name} /><FormField label="Branch" value={formData.bank_branch} onChange={v => setField('bank_branch', v)} /><FormField label="Letter Date" type="date" value={formData.date} onChange={v => setField('date', v)} /></div></div>{generated ? <div className="text-center text-xs text-emerald-600 font-medium p-3 bg-emerald-50 rounded-lg border border-emerald-200">✓ Bank Intro Letter generated.</div> : <Button onClick={handleGenerate} className="w-full text-white font-semibold h-9 bg-brand-red hover:bg-brand-red/90">Generate Bank Intro Letter</Button>}</>}</div></div><MismatchModal open={showMismatchModal} onClose={() => setShowMismatchModal(false)} mismatches={mismatches} onAction={handleMismatchAction} /></div>
}
