'use client'
import { useDocumentForm } from '@/hooks/useDocumentForm'
import { EmployeeSelect } from './EmployeeSelect'
import { FormField } from './FormField'
import { MismatchModal } from './MismatchModal'
import { Separator } from '@/components/ui/separator'
import { Button } from '@/components/ui/button'
import type { Employee } from '@/lib/storage'
import { validateRequiredFields } from '@/lib/validate'
interface EmbassyLetterFormData { name: string; designation: string; department: string; ref_code: string; date: string; passport_no: string; employee_id: string; joining_date: string; monthly_salary: string; leave_start: string; leave_end: string; embassy_name: string; embassy_location: string }
const initialData: EmbassyLetterFormData = { name: '', designation: '', department: '', ref_code: '', date: new Date().toISOString().slice(0, 10), passport_no: '', employee_id: '', joining_date: '', monthly_salary: '', leave_start: '', leave_end: '', embassy_name: '', embassy_location: '' }
function mapEmployeeToForm(emp: Employee): Partial<EmbassyLetterFormData> { return { name: emp.name, designation: emp.designation, department: emp.department, ref_code: emp.ref_code, employee_id: emp.id } }
function onCalculate(): Partial<EmbassyLetterFormData> { return {} }
export function EmbassyLetterForm() {
  const h = useDocumentForm({ docType: 'embassy_letter', initialData, mapEmployeeToForm, onCalculate, validate: (d) => validateRequiredFields(d, { name: { required: true, label: 'Name' }, designation: { required: true, label: 'Designation' }, passport_no: { required: true, label: 'Passport number' }, embassy_name: { required: true, label: 'Embassy name' } }) })
  const { formData, setField, selectedEmployeeId, handleEmployeeChange, employees, mismatches, showMismatchModal, setShowMismatchModal, handleGenerate, handleMismatchAction, generated, errors } = h
  const show = selectedEmployeeId && selectedEmployeeId !== '__new__'
  return <div className="flex flex-col h-full"><div className="flex-1 overflow-y-auto"><div className="p-4 space-y-4"><EmployeeSelect employees={employees} value={selectedEmployeeId} onChange={handleEmployeeChange} />{selectedEmployeeId === '__new__' && <div className="text-center text-xs text-gray-500 p-3 bg-gray-50 rounded-lg border border-gray-200">Please add employee first</div>}{show && <><Separator /><div className="space-y-3"><h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Employee Info</h4><div className="grid grid-cols-2 gap-x-3 gap-y-1"><FormField label="Name" value={formData.name} onChange={v => setField('name', v)} error={errors.name} /><FormField label="Designation" value={formData.designation} onChange={v => setField('designation', v)} error={errors.designation} /><FormField label="Department" value={formData.department} onChange={v => setField('department', v)} /><FormField label="Employee ID" value={formData.employee_id} onChange={v => setField('employee_id', v)} /><FormField label="Passport No." value={formData.passport_no} onChange={v => setField('passport_no', v)} error={errors.passport_no} /><FormField label="Ref Code" value={formData.ref_code} onChange={v => setField('ref_code', v)} /></div></div><Separator /><div className="space-y-3"><h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Employment & Travel Details</h4><div className="grid grid-cols-2 gap-x-3 gap-y-1"><FormField label="Joining Date" type="date" value={formData.joining_date} onChange={v => setField('joining_date', v)} /><FormField label="Monthly Salary (BDT)" value={formData.monthly_salary} onChange={v => setField('monthly_salary', v)} /><FormField label="Leave Start" type="date" value={formData.leave_start} onChange={v => setField('leave_start', v)} /><FormField label="Leave End" type="date" value={formData.leave_end} onChange={v => setField('leave_end', v)} /><FormField label="Embassy Name" value={formData.embassy_name} onChange={v => setField('embassy_name', v)} error={errors.embassy_name} /><FormField label="Embassy Location" value={formData.embassy_location} onChange={v => setField('embassy_location', v)} /><FormField label="Letter Date" type="date" value={formData.date} onChange={v => setField('date', v)} /></div></div>{generated ? <div className="text-center text-xs text-emerald-600 font-medium p-3 bg-emerald-50 rounded-lg border border-emerald-200">✓ Embassy Letter generated.</div> : <Button onClick={handleGenerate} className="w-full text-white font-semibold h-9 bg-brand-red hover:bg-brand-red/90">Generate Embassy Letter</Button>}</>}</div></div><MismatchModal open={showMismatchModal} onClose={() => setShowMismatchModal(false)} mismatches={mismatches} onAction={handleMismatchAction} /></div>
}
