'use client'
import { useDocumentForm } from '@/hooks/useDocumentForm'
import { EmployeeSelect } from './EmployeeSelect'
import { FormField } from './FormField'
import { MismatchModal } from './MismatchModal'
import { Separator } from '@/components/ui/separator'
import type { Employee } from '@/lib/storage'
import { validateRequiredFields } from '@/lib/validate'
import { AddEmployeeFirstNotice, GeneratedBanner, PrimaryActionButton, SectionHeading } from './FormPrimitives'
interface NOCLetterFormData { name: string; designation: string; department: string; ref_code: string; date: string; father_name: string; employee_id: string; joining_date: string; leaving_date: string; noc_purpose: string; noc_validity: string }
const initialData: NOCLetterFormData = { name: '', designation: '', department: '', ref_code: '', date: new Date().toISOString().slice(0, 10), father_name: '', employee_id: '', joining_date: '', leaving_date: '', noc_purpose: '', noc_validity: 'One Year' }
function mapEmployeeToForm(emp: Employee): Partial<NOCLetterFormData> { return { name: emp.name, designation: emp.designation, department: emp.department, ref_code: emp.ref_code, employee_id: emp.id } }
function onCalculate(): Partial<NOCLetterFormData> { return {} }
export function NOCLetterForm() {
  const h = useDocumentForm({ docType: 'noc_letter', initialData, mapEmployeeToForm, onCalculate, validate: (d) => validateRequiredFields(d, { name: { required: true, label: 'Name' }, designation: { required: true, label: 'Designation' }, father_name: { required: true, label: "Father's name" } }) })
  const { formData, setField, selectedEmployeeId, handleEmployeeChange, employees, mismatches, showMismatchModal, setShowMismatchModal, handleGenerate, handleMismatchAction, generated, errors } = h
  const show = selectedEmployeeId && selectedEmployeeId !== '__new__'
  return <div className="flex flex-col h-full"><div className="flex-1 overflow-y-auto"><div className="p-4 space-y-4"><EmployeeSelect employees={employees} value={selectedEmployeeId} onChange={handleEmployeeChange} />{selectedEmployeeId === '__new__' && <AddEmployeeFirstNotice />}{show && <><Separator /><div className="space-y-3"><SectionHeading>Employee Info</SectionHeading><div className="grid grid-cols-2 gap-x-3 gap-y-1"><FormField label="Name" value={formData.name} onChange={v => setField('name', v)} error={errors.name} /><FormField label="Father's Name" value={formData.father_name} onChange={v => setField('father_name', v)} error={errors.father_name} /><FormField label="Designation" value={formData.designation} onChange={v => setField('designation', v)} error={errors.designation} /><FormField label="Department" value={formData.department} onChange={v => setField('department', v)} /><FormField label="Employee ID" value={formData.employee_id} onChange={v => setField('employee_id', v)} /><FormField label="Ref Code" value={formData.ref_code} onChange={v => setField('ref_code', v)} /></div></div><Separator /><div className="space-y-3"><SectionHeading>NOC Details</SectionHeading><div className="grid grid-cols-2 gap-x-3 gap-y-1"><FormField label="Joining Date" type="date" value={formData.joining_date} onChange={v => setField('joining_date', v)} /><FormField label="Leaving Date" type="date" value={formData.leaving_date} onChange={v => setField('leaving_date', v)} /><FormField label="Purpose" value={formData.noc_purpose} onChange={v => setField('noc_purpose', v)} /><FormField label="Validity" value={formData.noc_validity} onChange={v => setField('noc_validity', v)} /><FormField label="Letter Date" type="date" value={formData.date} onChange={v => setField('date', v)} /></div></div>{generated ? <GeneratedBanner>✓ NOC Letter generated.</GeneratedBanner> : <PrimaryActionButton onClick={handleGenerate}>Generate NOC Letter</PrimaryActionButton>}</>}</div></div><MismatchModal open={showMismatchModal} onClose={() => setShowMismatchModal(false)} mismatches={mismatches} onAction={handleMismatchAction} /></div>
}
