'use client'
import { useDocumentForm } from '@/hooks/useDocumentForm'
import { EmployeeSelect } from './EmployeeSelect'
import { FormField } from './FormField'
import { MismatchModal } from './MismatchModal'
import { Separator } from '@/components/ui/separator'
import type { Employee } from '@/lib/storage'
import { validateRequiredFields } from '@/lib/validate'
import { AddEmployeeFirstNotice, GeneratedBanner, PrimaryActionButton, SectionHeading } from './FormPrimitives'
interface PIPLetterFormData { name: string; designation: string; department: string; ref_code: string; date: string; effective_date: string; pip_duration: string; performance_concerns: string; pip_goals: string; review_date: string; review_date_fmt: string }
const initialData: PIPLetterFormData = { name: '', designation: '', department: '', ref_code: '', date: new Date().toISOString().slice(0, 10), effective_date: '', pip_duration: '30', performance_concerns: '', pip_goals: '', review_date: '', review_date_fmt: '' }
function mapEmployeeToForm(emp: Employee): Partial<PIPLetterFormData> { return { name: emp.name, designation: emp.designation, department: emp.department, ref_code: emp.ref_code } }
function onCalculate(d: PIPLetterFormData): Partial<PIPLetterFormData> {
  const month = d.review_date ? new Date(d.review_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) : ''
  return { review_date_fmt: month, effective_date: d.effective_date } }
export function PIPLetterForm() {
  const h = useDocumentForm({ docType: 'pip_letter', initialData, mapEmployeeToForm, onCalculate, validate: (d) => validateRequiredFields(d, { name: { required: true, label: 'Name' }, designation: { required: true, label: 'Designation' }, department: { required: true, label: 'Department' }, performance_concerns: { required: true, label: 'Performance concerns' }, pip_goals: { required: true, label: 'PIP goals' } }) })
  const { formData, setField, selectedEmployeeId, handleEmployeeChange, employees, mismatches, showMismatchModal, setShowMismatchModal, handleGenerate, handleMismatchAction, generated, errors } = h
  const show = selectedEmployeeId && selectedEmployeeId !== '__new__'
  return <div className="flex flex-col h-full"><div className="flex-1 overflow-y-auto"><div className="p-4 space-y-4"><EmployeeSelect employees={employees} value={selectedEmployeeId} onChange={handleEmployeeChange} />{selectedEmployeeId === '__new__' && <AddEmployeeFirstNotice />}{show && <><Separator /><div className="space-y-3"><SectionHeading>Employee Info</SectionHeading><div className="grid grid-cols-2 gap-x-3 gap-y-1"><FormField label="Name" value={formData.name} onChange={v => setField('name', v)} error={errors.name} /><FormField label="Designation" value={formData.designation} onChange={v => setField('designation', v)} error={errors.designation} /><FormField label="Department" value={formData.department} onChange={v => setField('department', v)} error={errors.department} /><FormField label="Ref Code" value={formData.ref_code} onChange={v => setField('ref_code', v)} /></div></div><Separator /><div className="space-y-3"><SectionHeading>PIP Details</SectionHeading><div className="grid grid-cols-2 gap-x-3 gap-y-1"><FormField label="Effective Date" type="date" value={formData.effective_date} onChange={v => setField('effective_date', v)} /><FormField label="Duration (Days)" value={formData.pip_duration} onChange={v => setField('pip_duration', v)} /><FormField label="Review Date" type="date" value={formData.review_date} onChange={v => setField('review_date', v)} /><FormField label="Letter Date" type="date" value={formData.date} onChange={v => setField('date', v)} /></div><FormField label="Performance Concerns" value={formData.performance_concerns} onChange={v => setField('performance_concerns', v)} error={errors.performance_concerns} /><FormField label="Improvement Goals" value={formData.pip_goals} onChange={v => setField('pip_goals', v)} error={errors.pip_goals} /></div>{generated ? <GeneratedBanner>✓ PIP Letter generated.</GeneratedBanner> : <PrimaryActionButton onClick={handleGenerate}>Generate PIP Letter</PrimaryActionButton>}</>}</div></div><MismatchModal open={showMismatchModal} onClose={() => setShowMismatchModal(false)} mismatches={mismatches} onAction={handleMismatchAction} /></div>
}
